version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - echo `pwd`
      - npm build
      - npm test

reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: backend/output